exp: MinimalPair

mode:
  - analyze

predfpath: /Users/jeong/Projects/school/cosc426/cosc426/hw/hw05/predictions/bi_prediction.tsv

datafpath: /Users/jeong/Projects/school/cosc426/cosc426/hw/hw05/data/eval.tsv

resultsfpath: /Users/jeong/Projects/school/cosc426/cosc426/hw/hw05/results/bi_result.tsv

save: by_cond